// Code generated by scripts/generate_openapi.py; DO NOT EDIT.

package client

import (
	"context"
	"fmt"
	"net/url"
)

// OpenAPIClient is the generated low-level JSON API. Streaming workspace
// uploads and WebSocket sessions remain on Connection's custom adapters.
type OpenAPIClient struct {
	connection *Connection
}

// OpenAPI returns the generated low-level client bound to this connection.
func (c *Connection) OpenAPI() *OpenAPIClient {
	return &OpenAPIClient{connection: c}
}

type OpenAPIAppendAgentTaskEventQuery struct {
	AgentId *string
}

func (p OpenAPIAppendAgentTaskEventQuery) values() url.Values {
	values := url.Values{}
	if p.AgentId != nil {
		values.Set("agent_id", fmt.Sprint(*p.AgentId))
	}
	return values
}

type OpenAPIBlockAgentTaskQuery struct {
	AgentId *string
}

func (p OpenAPIBlockAgentTaskQuery) values() url.Values {
	values := url.Values{}
	if p.AgentId != nil {
		values.Set("agent_id", fmt.Sprint(*p.AgentId))
	}
	return values
}

type OpenAPICompleteAgentTaskQuery struct {
	AgentId *string
}

func (p OpenAPICompleteAgentTaskQuery) values() url.Values {
	values := url.Values{}
	if p.AgentId != nil {
		values.Set("agent_id", fmt.Sprint(*p.AgentId))
	}
	return values
}

type OpenAPICountWorkflowsQuery struct {
	Namespace *string
	Id        *string
	RunId     *string
	Type      *string
	Queue     *string
	State     *OpenAPIWorkflowState
	Query     *string
	Q         *string
	AgentId   *string
	Search    map[string]any
}

func (p OpenAPICountWorkflowsQuery) values() url.Values {
	values := url.Values{}
	if p.Namespace != nil {
		values.Set("namespace", fmt.Sprint(*p.Namespace))
	}
	if p.Id != nil {
		values.Set("id", fmt.Sprint(*p.Id))
	}
	if p.RunId != nil {
		values.Set("run_id", fmt.Sprint(*p.RunId))
	}
	if p.Type != nil {
		values.Set("type", fmt.Sprint(*p.Type))
	}
	if p.Queue != nil {
		values.Set("queue", fmt.Sprint(*p.Queue))
	}
	if p.State != nil {
		values.Set("state", fmt.Sprint(*p.State))
	}
	if p.Query != nil {
		values.Set("query", fmt.Sprint(*p.Query))
	}
	if p.Q != nil {
		values.Set("q", fmt.Sprint(*p.Q))
	}
	if p.AgentId != nil {
		values.Set("agent_id", fmt.Sprint(*p.AgentId))
	}
	for key, value := range p.Search {
		values.Set("search."+key, fmt.Sprint(value))
	}
	return values
}

type OpenAPIFailAgentTaskQuery struct {
	AgentId *string
}

func (p OpenAPIFailAgentTaskQuery) values() url.Values {
	values := url.Values{}
	if p.AgentId != nil {
		values.Set("agent_id", fmt.Sprint(*p.AgentId))
	}
	return values
}

type OpenAPIHeartbeatAgentTaskQuery struct {
	AgentId *string
}

func (p OpenAPIHeartbeatAgentTaskQuery) values() url.Values {
	values := url.Values{}
	if p.AgentId != nil {
		values.Set("agent_id", fmt.Sprint(*p.AgentId))
	}
	return values
}

type OpenAPIListSchedulesQuery struct {
	Namespace *string
	State     *OpenAPIScheduleState
	PageToken *string
	Limit     *int64
	Offset    *int64
}

func (p OpenAPIListSchedulesQuery) values() url.Values {
	values := url.Values{}
	if p.Namespace != nil {
		values.Set("namespace", fmt.Sprint(*p.Namespace))
	}
	if p.State != nil {
		values.Set("state", fmt.Sprint(*p.State))
	}
	if p.PageToken != nil {
		values.Set("page_token", fmt.Sprint(*p.PageToken))
	}
	if p.Limit != nil {
		values.Set("limit", fmt.Sprint(*p.Limit))
	}
	if p.Offset != nil {
		values.Set("offset", fmt.Sprint(*p.Offset))
	}
	return values
}

type OpenAPIListTasksQuery struct {
	Namespace *string
	Queue     *string
	Type      *string
	State     *OpenAPITaskState
	OrderBy   *string
	PageToken *string
	Limit     *int64
	Offset    *int64
}

func (p OpenAPIListTasksQuery) values() url.Values {
	values := url.Values{}
	if p.Namespace != nil {
		values.Set("namespace", fmt.Sprint(*p.Namespace))
	}
	if p.Queue != nil {
		values.Set("queue", fmt.Sprint(*p.Queue))
	}
	if p.Type != nil {
		values.Set("type", fmt.Sprint(*p.Type))
	}
	if p.State != nil {
		values.Set("state", fmt.Sprint(*p.State))
	}
	if p.OrderBy != nil {
		values.Set("order_by", fmt.Sprint(*p.OrderBy))
	}
	if p.PageToken != nil {
		values.Set("page_token", fmt.Sprint(*p.PageToken))
	}
	if p.Limit != nil {
		values.Set("limit", fmt.Sprint(*p.Limit))
	}
	if p.Offset != nil {
		values.Set("offset", fmt.Sprint(*p.Offset))
	}
	return values
}

type OpenAPIListWorkflowsQuery struct {
	Namespace *string
	Id        *string
	RunId     *string
	Type      *string
	Queue     *string
	State     *OpenAPIWorkflowState
	Query     *string
	Q         *string
	AgentId   *string
	OrderBy   *string
	Order     *string
	PageToken *string
	Search    map[string]any
	Limit     *int64
	Offset    *int64
}

func (p OpenAPIListWorkflowsQuery) values() url.Values {
	values := url.Values{}
	if p.Namespace != nil {
		values.Set("namespace", fmt.Sprint(*p.Namespace))
	}
	if p.Id != nil {
		values.Set("id", fmt.Sprint(*p.Id))
	}
	if p.RunId != nil {
		values.Set("run_id", fmt.Sprint(*p.RunId))
	}
	if p.Type != nil {
		values.Set("type", fmt.Sprint(*p.Type))
	}
	if p.Queue != nil {
		values.Set("queue", fmt.Sprint(*p.Queue))
	}
	if p.State != nil {
		values.Set("state", fmt.Sprint(*p.State))
	}
	if p.Query != nil {
		values.Set("query", fmt.Sprint(*p.Query))
	}
	if p.Q != nil {
		values.Set("q", fmt.Sprint(*p.Q))
	}
	if p.AgentId != nil {
		values.Set("agent_id", fmt.Sprint(*p.AgentId))
	}
	if p.OrderBy != nil {
		values.Set("order_by", fmt.Sprint(*p.OrderBy))
	}
	if p.Order != nil {
		values.Set("order", fmt.Sprint(*p.Order))
	}
	if p.PageToken != nil {
		values.Set("page_token", fmt.Sprint(*p.PageToken))
	}
	for key, value := range p.Search {
		values.Set("search."+key, fmt.Sprint(value))
	}
	if p.Limit != nil {
		values.Set("limit", fmt.Sprint(*p.Limit))
	}
	if p.Offset != nil {
		values.Set("offset", fmt.Sprint(*p.Offset))
	}
	return values
}

type OpenAPIPollAgentTaskQuery struct {
	Namespace    *string
	Queue        string
	AgentId      *string
	Version      *int64
	LogLevel     *string
	Capabilities []string
	WaitSeconds  *int64
	TaskTypes    *string
}

func (p OpenAPIPollAgentTaskQuery) values() url.Values {
	values := url.Values{}
	if p.Namespace != nil {
		values.Set("namespace", fmt.Sprint(*p.Namespace))
	}
	values.Set("queue", fmt.Sprint(p.Queue))
	if p.AgentId != nil {
		values.Set("agent_id", fmt.Sprint(*p.AgentId))
	}
	if p.Version != nil {
		values.Set("version", fmt.Sprint(*p.Version))
	}
	if p.LogLevel != nil {
		values.Set("log_level", fmt.Sprint(*p.LogLevel))
	}
	for _, value := range p.Capabilities {
		values.Add("capabilities", fmt.Sprint(value))
	}
	if p.WaitSeconds != nil {
		values.Set("wait_seconds", fmt.Sprint(*p.WaitSeconds))
	}
	if p.TaskTypes != nil {
		values.Set("task_types", fmt.Sprint(*p.TaskTypes))
	}
	return values
}

func (c *OpenAPIClient) AppendAgentTaskEvent(ctx context.Context, taskId string, query OpenAPIAppendAgentTaskEventQuery, body OpenAPIAppendAgentTaskEventRequestBody) (OpenAPIAppendAgentTaskEventResponseBody, error) {
	var response OpenAPIAppendAgentTaskEventResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIAppendAgentTaskEvent, map[string]string{"taskId": taskId}, query.values(), body, &response)
	return response, err
}
func (c *OpenAPIClient) BackfillSchedule(ctx context.Context, scheduleId string, body OpenAPIBackfillScheduleRequestBody) (OpenAPIBackfillScheduleResponseBody, error) {
	var response OpenAPIBackfillScheduleResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIBackfillSchedule, map[string]string{"scheduleId": scheduleId}, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) BlockAgentTask(ctx context.Context, taskId string, query OpenAPIBlockAgentTaskQuery, body OpenAPIBlockAgentTaskRequestBody) (OpenAPIBlockAgentTaskResponseBody, error) {
	var response OpenAPIBlockAgentTaskResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIBlockAgentTask, map[string]string{"taskId": taskId}, query.values(), body, &response)
	return response, err
}
func (c *OpenAPIClient) CancelWorkflow(ctx context.Context, workflowId string, body OpenAPICancelWorkflowRequestBody) (OpenAPICancelWorkflowResponseBody, error) {
	var response OpenAPICancelWorkflowResponseBody
	err := c.connection.doOpenAPI(ctx, openAPICancelWorkflow, map[string]string{"workflowId": workflowId}, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) Compact(ctx context.Context, body OpenAPICompactRequestBody) (OpenAPICompactResponseBody, error) {
	var response OpenAPICompactResponseBody
	err := c.connection.doOpenAPI(ctx, openAPICompact, nil, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) CompleteAgentTask(ctx context.Context, taskId string, query OpenAPICompleteAgentTaskQuery, body OpenAPICompleteAgentTaskRequestBody) (OpenAPICompleteAgentTaskResponseBody, error) {
	var response OpenAPICompleteAgentTaskResponseBody
	err := c.connection.doOpenAPI(ctx, openAPICompleteAgentTask, map[string]string{"taskId": taskId}, query.values(), body, &response)
	return response, err
}
func (c *OpenAPIClient) CountWorkflows(ctx context.Context, query OpenAPICountWorkflowsQuery) (OpenAPICountWorkflowsResponseBody, error) {
	var response OpenAPICountWorkflowsResponseBody
	err := c.connection.doOpenAPI(ctx, openAPICountWorkflows, nil, query.values(), nil, &response)
	return response, err
}
func (c *OpenAPIClient) CreateNamespace(ctx context.Context, body OpenAPICreateNamespaceRequestBody) (OpenAPICreateNamespaceResponseBody, error) {
	var response OpenAPICreateNamespaceResponseBody
	err := c.connection.doOpenAPI(ctx, openAPICreateNamespace, nil, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) CreateSandbox(ctx context.Context, body OpenAPICreateSandboxRequestBody) (OpenAPICreateSandboxResponseBody, error) {
	var response OpenAPICreateSandboxResponseBody
	err := c.connection.doOpenAPI(ctx, openAPICreateSandbox, nil, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) CreateSandboxSession(ctx context.Context, sandboxId string, body OpenAPICreateSandboxSessionRequestBody) (OpenAPICreateSandboxSessionResponseBody, error) {
	var response OpenAPICreateSandboxSessionResponseBody
	err := c.connection.doOpenAPI(ctx, openAPICreateSandboxSession, map[string]string{"sandboxId": sandboxId}, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) CreateSchedule(ctx context.Context, body OpenAPICreateScheduleRequestBody) (OpenAPICreateScheduleResponseBody, error) {
	var response OpenAPICreateScheduleResponseBody
	err := c.connection.doOpenAPI(ctx, openAPICreateSchedule, nil, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) DeleteSandbox(ctx context.Context, sandboxId string) (OpenAPIDeleteSandboxResponseBody, error) {
	var response OpenAPIDeleteSandboxResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIDeleteSandbox, map[string]string{"sandboxId": sandboxId}, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) DeleteSchedule(ctx context.Context, scheduleId string) (OpenAPIDeleteScheduleResponseBody, error) {
	var response OpenAPIDeleteScheduleResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIDeleteSchedule, map[string]string{"scheduleId": scheduleId}, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) EnqueueTask(ctx context.Context, body OpenAPIEnqueueTaskRequestBody) (OpenAPIEnqueueTaskResponseBody, error) {
	var response OpenAPIEnqueueTaskResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIEnqueueTask, nil, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) FailAgentTask(ctx context.Context, taskId string, query OpenAPIFailAgentTaskQuery, body OpenAPIFailAgentTaskRequestBody) (OpenAPIFailAgentTaskResponseBody, error) {
	var response OpenAPIFailAgentTaskResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIFailAgentTask, map[string]string{"taskId": taskId}, query.values(), body, &response)
	return response, err
}
func (c *OpenAPIClient) GetSandbox(ctx context.Context, sandboxId string) (OpenAPIGetSandboxResponseBody, error) {
	var response OpenAPIGetSandboxResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIGetSandbox, map[string]string{"sandboxId": sandboxId}, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) GetSchedule(ctx context.Context, scheduleId string) (OpenAPIGetScheduleResponseBody, error) {
	var response OpenAPIGetScheduleResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIGetSchedule, map[string]string{"scheduleId": scheduleId}, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) GetTask(ctx context.Context, taskId string) (OpenAPIGetTaskResponseBody, error) {
	var response OpenAPIGetTaskResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIGetTask, map[string]string{"taskId": taskId}, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) GetWorkflow(ctx context.Context, workflowId string) (OpenAPIGetWorkflowResponseBody, error) {
	var response OpenAPIGetWorkflowResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIGetWorkflow, map[string]string{"workflowId": workflowId}, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) Health(ctx context.Context) (OpenAPIHealthResponseBody, error) {
	var response OpenAPIHealthResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIHealth, nil, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) HeartbeatAgentTask(ctx context.Context, taskId string, query OpenAPIHeartbeatAgentTaskQuery, body OpenAPIHeartbeatAgentTaskRequestBody) (OpenAPIHeartbeatAgentTaskResponseBody, error) {
	var response OpenAPIHeartbeatAgentTaskResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIHeartbeatAgentTask, map[string]string{"taskId": taskId}, query.values(), body, &response)
	return response, err
}
func (c *OpenAPIClient) ListNamespaces(ctx context.Context) (OpenAPIListNamespacesResponseBody, error) {
	var response OpenAPIListNamespacesResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIListNamespaces, nil, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) ListSandboxes(ctx context.Context) (OpenAPIListSandboxesResponseBody, error) {
	var response OpenAPIListSandboxesResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIListSandboxes, nil, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) ListSchedules(ctx context.Context, query OpenAPIListSchedulesQuery) (OpenAPIListSchedulesResponseBody, error) {
	var response OpenAPIListSchedulesResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIListSchedules, nil, query.values(), nil, &response)
	return response, err
}
func (c *OpenAPIClient) ListTaskEvents(ctx context.Context, taskId string) (OpenAPIListTaskEventsResponseBody, error) {
	var response OpenAPIListTaskEventsResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIListTaskEvents, map[string]string{"taskId": taskId}, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) ListTasks(ctx context.Context, query OpenAPIListTasksQuery) (OpenAPIListTasksResponseBody, error) {
	var response OpenAPIListTasksResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIListTasks, nil, query.values(), nil, &response)
	return response, err
}
func (c *OpenAPIClient) ListWorkflowHistory(ctx context.Context, workflowId string) (OpenAPIListWorkflowHistoryResponseBody, error) {
	var response OpenAPIListWorkflowHistoryResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIListWorkflowHistory, map[string]string{"workflowId": workflowId}, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) ListWorkflows(ctx context.Context, query OpenAPIListWorkflowsQuery) (OpenAPIListWorkflowsResponseBody, error) {
	var response OpenAPIListWorkflowsResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIListWorkflows, nil, query.values(), nil, &response)
	return response, err
}
func (c *OpenAPIClient) PauseSchedule(ctx context.Context, scheduleId string, body OpenAPIPauseScheduleRequestBody) (OpenAPIPauseScheduleResponseBody, error) {
	var response OpenAPIPauseScheduleResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIPauseSchedule, map[string]string{"scheduleId": scheduleId}, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) PollAgentTask(ctx context.Context, query OpenAPIPollAgentTaskQuery) (OpenAPIPollAgentTaskResponseBody, error) {
	var response OpenAPIPollAgentTaskResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIPollAgentTask, nil, query.values(), nil, &response)
	return response, err
}
func (c *OpenAPIClient) Ready(ctx context.Context) (OpenAPIReadyResponseBody, error) {
	var response OpenAPIReadyResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIReady, nil, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) RefreshAgentSession(ctx context.Context, body OpenAPIRefreshAgentSessionRequestBody) (OpenAPIRefreshAgentSessionResponseBody, error) {
	var response OpenAPIRefreshAgentSessionResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIRefreshAgentSession, nil, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) SignalWithStartWorkflow(ctx context.Context, workflowId string, body OpenAPISignalWithStartWorkflowRequestBody) (OpenAPISignalWithStartWorkflowResponseBody, error) {
	var response OpenAPISignalWithStartWorkflowResponseBody
	err := c.connection.doOpenAPI(ctx, openAPISignalWithStartWorkflow, map[string]string{"workflowId": workflowId}, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) SignalWorkflow(ctx context.Context, workflowId string, body OpenAPISignalWorkflowRequestBody) (OpenAPISignalWorkflowResponseBody, error) {
	var response OpenAPISignalWorkflowResponseBody
	err := c.connection.doOpenAPI(ctx, openAPISignalWorkflow, map[string]string{"workflowId": workflowId}, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) StartSandbox(ctx context.Context, sandboxId string) (OpenAPIStartSandboxResponseBody, error) {
	var response OpenAPIStartSandboxResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIStartSandbox, map[string]string{"sandboxId": sandboxId}, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) StopSandbox(ctx context.Context, sandboxId string) (OpenAPIStopSandboxResponseBody, error) {
	var response OpenAPIStopSandboxResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIStopSandbox, map[string]string{"sandboxId": sandboxId}, nil, nil, &response)
	return response, err
}
func (c *OpenAPIClient) TerminateWorkflow(ctx context.Context, workflowId string, body OpenAPITerminateWorkflowRequestBody) (OpenAPITerminateWorkflowResponseBody, error) {
	var response OpenAPITerminateWorkflowResponseBody
	err := c.connection.doOpenAPI(ctx, openAPITerminateWorkflow, map[string]string{"workflowId": workflowId}, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) TriggerSchedule(ctx context.Context, scheduleId string, body OpenAPITriggerScheduleRequestBody) (OpenAPITriggerScheduleResponseBody, error) {
	var response OpenAPITriggerScheduleResponseBody
	err := c.connection.doOpenAPI(ctx, openAPITriggerSchedule, map[string]string{"scheduleId": scheduleId}, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) UnpauseSchedule(ctx context.Context, scheduleId string, body OpenAPIUnpauseScheduleRequestBody) (OpenAPIUnpauseScheduleResponseBody, error) {
	var response OpenAPIUnpauseScheduleResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIUnpauseSchedule, map[string]string{"scheduleId": scheduleId}, nil, body, &response)
	return response, err
}
func (c *OpenAPIClient) UpdateSchedule(ctx context.Context, scheduleId string, body OpenAPIUpdateScheduleRequestBody) (OpenAPIUpdateScheduleResponseBody, error) {
	var response OpenAPIUpdateScheduleResponseBody
	err := c.connection.doOpenAPI(ctx, openAPIUpdateSchedule, map[string]string{"scheduleId": scheduleId}, nil, body, &response)
	return response, err
}

// OpenAPIClientOperationCount excludes the streaming upload and WebSocket
// connection operations, which use Connection's custom adapters.
const OpenAPIClientOperationCount = 40

const openAPIClientSpecSHA256 = "290703b21b11d91df949108588527908c4e907a61b30f69947489048af87b0d8"
