// Code generated by scripts/generate_openapi.py; DO NOT EDIT.

package client

import (
	protocol "github.com/postgrip-io/postgrip-agent-sdks/protocol"
)

// These public models provide a complete, generated low-level wire surface.
// Existing protocol aliases remain compatibility adapters for the ergonomic SDK.
type OpenAPINoBody struct{}

type OpenAPIJsonValue = any
type OpenAPIHealthResponse struct {
	Status string `json:"status"`
}
type OpenAPIReadyResponse struct {
	Status string           `json:"status"`
	Stats  map[string]int64 `json:"stats"`
}
type OpenAPITaskState = protocol.TaskState
type OpenAPITaskEventKind = protocol.TaskEventKind
type OpenAPIAgentPollDirectiveType string
type OpenAPIAgentPollDirectiveSubject string
type OpenAPIWorkflowState = protocol.WorkflowState
type OpenAPIWorkflowIdReusePolicy = protocol.WorkflowIDReusePolicy
type OpenAPIScheduleState = protocol.ScheduleState
type OpenAPIScheduleOverlapPolicy = protocol.ScheduleOverlapPolicy
type OpenAPIScheduleMissedRunPolicy = protocol.ScheduleMissedRunPolicy
type OpenAPISandboxBackend = protocol.SandboxBackend
type OpenAPISandboxDesiredState = protocol.SandboxDesiredState
type OpenAPISandboxObservedState = protocol.SandboxObservedState
type OpenAPISandboxSessionKind string
type OpenAPINamespace = protocol.Namespace
type OpenAPICreateNamespaceRequest = protocol.CreateNamespaceRequest
type OpenAPICompactRequest = protocol.CompactRequest
type OpenAPICompactResponse = protocol.CompactResponse
type OpenAPIEnqueueTaskRequest = protocol.EnqueueTaskRequest
type OpenAPITask = protocol.Task
type OpenAPITaskResult = protocol.TaskResult
type OpenAPIFailureInfo = protocol.FailureInfo
type OpenAPIContinueAsNewResult = protocol.ContinueAsNewResult
type OpenAPITaskEventInput = protocol.TaskEventInput
type OpenAPITaskEvent = protocol.TaskEvent
type OpenAPIRetryPolicy = protocol.RetryPolicy
type OpenAPIScheduleCalendarSpec = protocol.ScheduleCalendarSpec
type OpenAPIScheduleSpec = protocol.ScheduleSpec
type OpenAPIScheduleAction = protocol.ScheduleAction
type OpenAPISchedule = protocol.Schedule
type OpenAPICreateScheduleRequest = protocol.CreateScheduleRequest
type OpenAPIUpdateScheduleRequest = protocol.UpdateScheduleRequest
type OpenAPIPauseScheduleRequest = protocol.PauseScheduleRequest
type OpenAPIUnpauseScheduleRequest = protocol.UnpauseScheduleRequest
type OpenAPITriggerScheduleRequest = protocol.TriggerScheduleRequest
type OpenAPITriggerScheduleResponse = protocol.TriggerScheduleResponse
type OpenAPIBackfillScheduleRequest = protocol.BackfillScheduleRequest
type OpenAPIBackfillScheduleResponse = protocol.BackfillScheduleResponse
type OpenAPIWorkflowExecution = protocol.WorkflowExecution
type OpenAPIWorkflowHistoryEvent = protocol.WorkflowHistoryEvent
type OpenAPIWorkflowCountResponse = protocol.WorkflowCountResponse
type OpenAPISignalWorkflowRequest = protocol.SignalWorkflowRequest
type OpenAPISignalWithStartWorkflowRequest = protocol.SignalWithStartWorkflowRequest
type OpenAPISignalWithStartWorkflowResponse = protocol.SignalWithStartWorkflowResponse
type OpenAPICancelWorkflowRequest = protocol.CancelWorkflowRequest
type OpenAPITerminateWorkflowRequest = protocol.TerminateWorkflowRequest
type OpenAPIAgentPollDirective = protocol.AgentPollDirective
type OpenAPIPollTaskResponse = protocol.PollTaskResponse
type OpenAPIHeartbeatTaskRequest = protocol.HeartbeatTaskRequest
type OpenAPIAppendTaskEventRequest = protocol.AppendTaskEventRequest
type OpenAPICompleteTaskRequest = protocol.CompleteTaskRequest
type OpenAPIBlockTaskRequest = protocol.BlockTaskRequest
type OpenAPIFailTaskRequest = protocol.FailTaskRequest
type OpenAPIRefreshAgentSessionRequest = protocol.RefreshAgentSessionRequest
type OpenAPIAgentSessionResponse = protocol.AgentSessionResponse
type OpenAPISandboxResourceLimits = protocol.SandboxResourceLimits
type OpenAPISandboxPortMapping = protocol.SandboxPortMapping
type OpenAPISandboxNetworkPolicy = protocol.SandboxNetworkPolicy
type OpenAPISandbox = protocol.Sandbox
type OpenAPISandboxCreateRequest = protocol.SandboxCreateRequest
type OpenAPISandboxListResponse = protocol.SandboxListResponse
type OpenAPICreateSandboxSessionRequest = protocol.CreateSandboxSessionRequest
type OpenAPICreateSandboxSessionResponse = protocol.CreateSandboxSessionResponse
type OpenAPISandboxWorkspace = protocol.SandboxWorkspace
type OpenAPIErrorResponse struct {
	Error string  `json:"error"`
	Code  *string `json:"code,omitempty"`
}
type OpenAPIAppendAgentTaskEventRequestBody = OpenAPIAppendTaskEventRequest
type OpenAPIAppendAgentTaskEventResponseBody = OpenAPITaskEvent
type OpenAPIBackfillScheduleRequestBody = OpenAPIBackfillScheduleRequest
type OpenAPIBackfillScheduleResponseBody = OpenAPIBackfillScheduleResponse
type OpenAPIBlockAgentTaskRequestBody = OpenAPIBlockTaskRequest
type OpenAPIBlockAgentTaskResponseBody = OpenAPITask
type OpenAPICancelWorkflowRequestBody = OpenAPICancelWorkflowRequest
type OpenAPICancelWorkflowResponseBody = OpenAPIWorkflowHistoryEvent
type OpenAPICompactRequestBody = OpenAPICompactRequest
type OpenAPICompactResponseBody = OpenAPICompactResponse
type OpenAPICompleteAgentTaskRequestBody = OpenAPICompleteTaskRequest
type OpenAPICompleteAgentTaskResponseBody = OpenAPITask
type OpenAPIConnectSandboxSessionRequestBody = OpenAPINoBody
type OpenAPIConnectSandboxSessionResponseBody = OpenAPINoBody
type OpenAPICountWorkflowsRequestBody = OpenAPINoBody
type OpenAPICountWorkflowsResponseBody = OpenAPIWorkflowCountResponse
type OpenAPICreateNamespaceRequestBody = OpenAPICreateNamespaceRequest
type OpenAPICreateNamespaceResponseBody = OpenAPINamespace
type OpenAPICreateSandboxRequestBody = OpenAPISandboxCreateRequest
type OpenAPICreateSandboxResponseBody = OpenAPISandbox
type OpenAPICreateSandboxSessionRequestBody = OpenAPICreateSandboxSessionRequest
type OpenAPICreateSandboxSessionResponseBody = OpenAPICreateSandboxSessionResponse
type OpenAPICreateScheduleRequestBody = OpenAPICreateScheduleRequest
type OpenAPICreateScheduleResponseBody = OpenAPISchedule
type OpenAPIDeleteSandboxRequestBody = OpenAPINoBody
type OpenAPIDeleteSandboxResponseBody = OpenAPISandbox
type OpenAPIDeleteScheduleRequestBody = OpenAPINoBody
type OpenAPIDeleteScheduleResponseBody = OpenAPISchedule
type OpenAPIEnqueueTaskRequestBody = OpenAPIEnqueueTaskRequest
type OpenAPIEnqueueTaskResponseBody = OpenAPITask
type OpenAPIFailAgentTaskRequestBody = OpenAPIFailTaskRequest
type OpenAPIFailAgentTaskResponseBody = OpenAPITask
type OpenAPIGetSandboxRequestBody = OpenAPINoBody
type OpenAPIGetSandboxResponseBody = OpenAPISandbox
type OpenAPIGetScheduleRequestBody = OpenAPINoBody
type OpenAPIGetScheduleResponseBody = OpenAPISchedule
type OpenAPIGetTaskRequestBody = OpenAPINoBody
type OpenAPIGetTaskResponseBody = OpenAPITask
type OpenAPIGetWorkflowRequestBody = OpenAPINoBody
type OpenAPIGetWorkflowResponseBody = OpenAPIWorkflowExecution
type OpenAPIHealthRequestBody = OpenAPINoBody
type OpenAPIHealthResponseBody = OpenAPIHealthResponse
type OpenAPIHeartbeatAgentTaskRequestBody = OpenAPIHeartbeatTaskRequest
type OpenAPIHeartbeatAgentTaskResponseBody = OpenAPITask
type OpenAPIListNamespacesRequestBody = OpenAPINoBody
type OpenAPIListNamespacesResponseBody = []OpenAPINamespace
type OpenAPIListSandboxesRequestBody = OpenAPINoBody
type OpenAPIListSandboxesResponseBody = OpenAPISandboxListResponse
type OpenAPIListSchedulesRequestBody = OpenAPINoBody
type OpenAPIListSchedulesResponseBody = []OpenAPISchedule
type OpenAPIListTaskEventsRequestBody = OpenAPINoBody
type OpenAPIListTaskEventsResponseBody = []OpenAPITaskEvent
type OpenAPIListTasksRequestBody = OpenAPINoBody
type OpenAPIListTasksResponseBody = []OpenAPITask
type OpenAPIListWorkflowHistoryRequestBody = OpenAPINoBody
type OpenAPIListWorkflowHistoryResponseBody = []OpenAPIWorkflowHistoryEvent
type OpenAPIListWorkflowsRequestBody = OpenAPINoBody
type OpenAPIListWorkflowsResponseBody = []OpenAPIWorkflowExecution
type OpenAPIPauseScheduleRequestBody = OpenAPIPauseScheduleRequest
type OpenAPIPauseScheduleResponseBody = OpenAPISchedule
type OpenAPIPollAgentTaskRequestBody = OpenAPINoBody
type OpenAPIPollAgentTaskResponseBody = OpenAPIPollTaskResponse
type OpenAPIReadyRequestBody = OpenAPINoBody
type OpenAPIReadyResponseBody = OpenAPIReadyResponse
type OpenAPIRefreshAgentSessionRequestBody = OpenAPIRefreshAgentSessionRequest
type OpenAPIRefreshAgentSessionResponseBody = OpenAPIAgentSessionResponse
type OpenAPISignalWithStartWorkflowRequestBody = OpenAPISignalWithStartWorkflowRequest
type OpenAPISignalWithStartWorkflowResponseBody = OpenAPISignalWithStartWorkflowResponse
type OpenAPISignalWorkflowRequestBody = OpenAPISignalWorkflowRequest
type OpenAPISignalWorkflowResponseBody = OpenAPIWorkflowHistoryEvent
type OpenAPIStartSandboxRequestBody = OpenAPINoBody
type OpenAPIStartSandboxResponseBody = OpenAPISandbox
type OpenAPIStopSandboxRequestBody = OpenAPINoBody
type OpenAPIStopSandboxResponseBody = OpenAPISandbox
type OpenAPITerminateWorkflowRequestBody = OpenAPITerminateWorkflowRequest
type OpenAPITerminateWorkflowResponseBody = OpenAPIWorkflowHistoryEvent
type OpenAPITriggerScheduleRequestBody = OpenAPITriggerScheduleRequest
type OpenAPITriggerScheduleResponseBody = OpenAPITriggerScheduleResponse
type OpenAPIUnpauseScheduleRequestBody = OpenAPIUnpauseScheduleRequest
type OpenAPIUnpauseScheduleResponseBody = OpenAPISchedule
type OpenAPIUpdateScheduleRequestBody = OpenAPIUpdateScheduleRequest
type OpenAPIUpdateScheduleResponseBody = OpenAPISchedule
type OpenAPIUploadWorkspaceRequestBody = []byte
type OpenAPIUploadWorkspaceResponseBody = OpenAPISandboxWorkspace

// OpenAPI-prefixed constants expose every generated enum value without
// colliding with the ergonomic SDK's compatibility constants.
const (
	OpenAPITaskStateQueued                               OpenAPITaskState                 = "queued"
	OpenAPITaskStateLeased                               OpenAPITaskState                 = "leased"
	OpenAPITaskStateBlocked                              OpenAPITaskState                 = "blocked"
	OpenAPITaskStateSucceeded                            OpenAPITaskState                 = "succeeded"
	OpenAPITaskStateFailed                               OpenAPITaskState                 = "failed"
	OpenAPITaskEventKindLeased                           OpenAPITaskEventKind             = "leased"
	OpenAPITaskEventKindStarted                          OpenAPITaskEventKind             = "started"
	OpenAPITaskEventKindHeartbeat                        OpenAPITaskEventKind             = "heartbeat"
	OpenAPITaskEventKindMilestone                        OpenAPITaskEventKind             = "milestone"
	OpenAPITaskEventKindProgress                         OpenAPITaskEventKind             = "progress"
	OpenAPITaskEventKindStdout                           OpenAPITaskEventKind             = "stdout"
	OpenAPITaskEventKindStderr                           OpenAPITaskEventKind             = "stderr"
	OpenAPITaskEventKindCompleted                        OpenAPITaskEventKind             = "completed"
	OpenAPITaskEventKindFailed                           OpenAPITaskEventKind             = "failed"
	OpenAPIAgentPollDirectiveTypeUpgrade                 OpenAPIAgentPollDirectiveType    = "upgrade"
	OpenAPIAgentPollDirectiveTypeShutdown                OpenAPIAgentPollDirectiveType    = "shutdown"
	OpenAPIAgentPollDirectiveTypeLogLevel                OpenAPIAgentPollDirectiveType    = "log_level"
	OpenAPIAgentPollDirectiveTypePollNow                 OpenAPIAgentPollDirectiveType    = "poll_now"
	OpenAPIAgentPollDirectiveTypeAttest                  OpenAPIAgentPollDirectiveType    = "attest"
	OpenAPIAgentPollDirectiveSubjectAgent                OpenAPIAgentPollDirectiveSubject = "agent"
	OpenAPIAgentPollDirectiveSubjectAgentHelper          OpenAPIAgentPollDirectiveSubject = "agent_helper"
	OpenAPIWorkflowStateRunning                          OpenAPIWorkflowState             = "running"
	OpenAPIWorkflowStateSucceeded                        OpenAPIWorkflowState             = "succeeded"
	OpenAPIWorkflowStateFailed                           OpenAPIWorkflowState             = "failed"
	OpenAPIWorkflowStateContinuedAsNew                   OpenAPIWorkflowState             = "continued_as_new"
	OpenAPIWorkflowIdReusePolicyAllowDuplicate           OpenAPIWorkflowIdReusePolicy     = "allow_duplicate"
	OpenAPIWorkflowIdReusePolicyAllowDuplicateFailedOnly OpenAPIWorkflowIdReusePolicy     = "allow_duplicate_failed_only"
	OpenAPIWorkflowIdReusePolicyRejectDuplicate          OpenAPIWorkflowIdReusePolicy     = "reject_duplicate"
	OpenAPIScheduleStateActive                           OpenAPIScheduleState             = "active"
	OpenAPIScheduleStatePaused                           OpenAPIScheduleState             = "paused"
	OpenAPIScheduleStateDeleted                          OpenAPIScheduleState             = "deleted"
	OpenAPIScheduleOverlapPolicySkip                     OpenAPIScheduleOverlapPolicy     = "skip"
	OpenAPIScheduleOverlapPolicyAllowAll                 OpenAPIScheduleOverlapPolicy     = "allow_all"
	OpenAPIScheduleMissedRunPolicyCatchUp                OpenAPIScheduleMissedRunPolicy   = "catch_up"
	OpenAPIScheduleMissedRunPolicySkip                   OpenAPIScheduleMissedRunPolicy   = "skip"
	OpenAPISandboxBackendAuto                            OpenAPISandboxBackend            = "auto"
	OpenAPISandboxBackendDocker                          OpenAPISandboxBackend            = "docker"
	OpenAPISandboxBackendPodman                          OpenAPISandboxBackend            = "podman"
	OpenAPISandboxBackendFirecracker                     OpenAPISandboxBackend            = "firecracker"
	OpenAPISandboxDesiredStateRunning                    OpenAPISandboxDesiredState       = "running"
	OpenAPISandboxDesiredStateStopped                    OpenAPISandboxDesiredState       = "stopped"
	OpenAPISandboxDesiredStateDeleted                    OpenAPISandboxDesiredState       = "deleted"
	OpenAPISandboxObservedStateRequested                 OpenAPISandboxObservedState      = "requested"
	OpenAPISandboxObservedStateScheduling                OpenAPISandboxObservedState      = "scheduling"
	OpenAPISandboxObservedStateProvisioning              OpenAPISandboxObservedState      = "provisioning"
	OpenAPISandboxObservedStateSettingUp                 OpenAPISandboxObservedState      = "setting_up"
	OpenAPISandboxObservedStateRunning                   OpenAPISandboxObservedState      = "running"
	OpenAPISandboxObservedStateStopping                  OpenAPISandboxObservedState      = "stopping"
	OpenAPISandboxObservedStateStopped                   OpenAPISandboxObservedState      = "stopped"
	OpenAPISandboxObservedStateStarting                  OpenAPISandboxObservedState      = "starting"
	OpenAPISandboxObservedStateDeleting                  OpenAPISandboxObservedState      = "deleting"
	OpenAPISandboxObservedStateDeleted                   OpenAPISandboxObservedState      = "deleted"
	OpenAPISandboxObservedStateFailed                    OpenAPISandboxObservedState      = "failed"
	OpenAPISandboxSessionKindPty                         OpenAPISandboxSessionKind        = "pty"
	OpenAPISandboxSessionKindExec                        OpenAPISandboxSessionKind        = "exec"
)

// Compatibility names preserve the existing SDK surface while making the
// generated OpenAPI models its implementation.
type JsonValue = OpenAPIJsonValue
type HealthResponse = OpenAPIHealthResponse
type ReadyResponse = OpenAPIReadyResponse
type TaskState = protocol.TaskState
type TaskEventKind = protocol.TaskEventKind
type AgentPollDirectiveType = OpenAPIAgentPollDirectiveType
type AgentPollDirectiveSubject = OpenAPIAgentPollDirectiveSubject
type WorkflowState = protocol.WorkflowState
type WorkflowIdReusePolicy = protocol.WorkflowIDReusePolicy
type ScheduleState = protocol.ScheduleState
type ScheduleOverlapPolicy = protocol.ScheduleOverlapPolicy
type ScheduleMissedRunPolicy = protocol.ScheduleMissedRunPolicy
type SandboxBackend = protocol.SandboxBackend
type SandboxDesiredState = protocol.SandboxDesiredState
type SandboxObservedState = protocol.SandboxObservedState
type SandboxSessionKind = OpenAPISandboxSessionKind
type Namespace = protocol.Namespace
type CreateNamespaceRequest = protocol.CreateNamespaceRequest
type CompactRequest = protocol.CompactRequest
type CompactResponse = protocol.CompactResponse
type EnqueueTaskRequest = protocol.EnqueueTaskRequest
type Task = protocol.Task
type TaskResult = protocol.TaskResult
type FailureInfo = protocol.FailureInfo
type ContinueAsNewResult = protocol.ContinueAsNewResult
type TaskEventInput = protocol.TaskEventInput
type TaskEvent = protocol.TaskEvent
type RetryPolicy = protocol.RetryPolicy
type ScheduleCalendarSpec = protocol.ScheduleCalendarSpec
type ScheduleSpec = protocol.ScheduleSpec
type ScheduleAction = protocol.ScheduleAction
type Schedule = protocol.Schedule
type CreateScheduleRequest = protocol.CreateScheduleRequest
type UpdateScheduleRequest = protocol.UpdateScheduleRequest
type PauseScheduleRequest = protocol.PauseScheduleRequest
type UnpauseScheduleRequest = protocol.UnpauseScheduleRequest
type TriggerScheduleRequest = protocol.TriggerScheduleRequest
type TriggerScheduleResponse = protocol.TriggerScheduleResponse
type BackfillScheduleRequest = protocol.BackfillScheduleRequest
type BackfillScheduleResponse = protocol.BackfillScheduleResponse
type WorkflowExecution = protocol.WorkflowExecution
type WorkflowHistoryEvent = protocol.WorkflowHistoryEvent
type WorkflowCountResponse = protocol.WorkflowCountResponse
type SignalWorkflowRequest = protocol.SignalWorkflowRequest
type SignalWithStartWorkflowRequest = protocol.SignalWithStartWorkflowRequest
type SignalWithStartWorkflowResponse = protocol.SignalWithStartWorkflowResponse
type CancelWorkflowRequest = protocol.CancelWorkflowRequest
type TerminateWorkflowRequest = protocol.TerminateWorkflowRequest
type AgentPollDirective = protocol.AgentPollDirective
type PollTaskResponse = protocol.PollTaskResponse
type HeartbeatTaskRequest = protocol.HeartbeatTaskRequest
type AppendTaskEventRequest = protocol.AppendTaskEventRequest
type CompleteTaskRequest = protocol.CompleteTaskRequest
type BlockTaskRequest = protocol.BlockTaskRequest
type FailTaskRequest = protocol.FailTaskRequest
type RefreshAgentSessionRequest = protocol.RefreshAgentSessionRequest
type AgentSessionResponse = protocol.AgentSessionResponse
type SandboxResourceLimits = protocol.SandboxResourceLimits
type SandboxPortMapping = protocol.SandboxPortMapping
type SandboxNetworkPolicy = protocol.SandboxNetworkPolicy
type Sandbox = protocol.Sandbox
type SandboxCreateRequest = protocol.SandboxCreateRequest
type SandboxListResponse = protocol.SandboxListResponse
type CreateSandboxSessionRequest = protocol.CreateSandboxSessionRequest
type CreateSandboxSessionResponse = protocol.CreateSandboxSessionResponse
type SandboxWorkspace = protocol.SandboxWorkspace

const openAPITypesSpecSHA256 = "0d323cc601cc71a08146b3395f479bb6702a9ad3d5f40f5917ef064140f813cb"
