#!/usr/bin/env python3
"""Generate the SDKs' internal HTTP operation bindings from openapi.json."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "openapi.json"
HTTP_METHODS = {"delete", "get", "head", "options", "patch", "post", "put", "trace"}


def load_contract() -> tuple[dict[str, Any], str]:
    raw = SPEC_PATH.read_bytes()
    spec = json.loads(raw)
    if not str(spec.get("openapi", "")).startswith("3.1."):
        raise ValueError("openapi.json must use OpenAPI 3.1")
    return spec, hashlib.sha256(raw).hexdigest()


def operation_rows(spec: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    seen: set[str] = set()
    for route_path, path_item in spec.get("paths", {}).items():
        for method, operation in path_item.items():
            if method not in HTTP_METHODS or not operation.get("x-postgrip-sdk-generate"):
                continue
            operation_id = operation.get("operationId")
            if not operation_id or operation_id in seen:
                raise ValueError(f"missing or duplicate operationId: {operation_id!r}")
            seen.add(operation_id)
            rows.append(
                {
                    "id": operation_id,
                    "method": method.upper(),
                    "path": route_path,
                    "auth": operation.get("x-postgrip-auth-lane", ""),
                    "signing": operation.get("x-postgrip-request-signing", ""),
                    "streaming": bool(operation.get("x-postgrip-streaming-request")),
                    "websocket": bool(operation.get("x-postgrip-websocket")),
                    "parameters": re.findall(r"\{([^}]+)\}", route_path),
                }
            )
    if not rows:
        raise ValueError("openapi.json contains no generated operations")
    return sorted(rows, key=lambda row: row["id"])


def go_name(operation_id: str) -> str:
    return operation_id[:1].upper() + operation_id[1:]


def snake_name(operation_id: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", operation_id).upper()


def go_source(rows: list[dict[str, Any]], digest: str) -> str:
    constants = "\n".join(
        f'\topenAPI{go_name(row["id"])} openAPIOperationID = {json.dumps(row["id"])}'
        for row in rows
    )
    table_rows = []
    for row in rows:
        parameters = ", ".join(json.dumps(value) for value in row["parameters"])
        table_rows.append(
            f'\topenAPI{go_name(row["id"])}: {{Method: {json.dumps(row["method"])}, '
            f'Path: {json.dumps(row["path"])}, AuthLane: {json.dumps(row["auth"])}, '
            f'Signing: {json.dumps(row["signing"])}, StreamingRequest: {str(row["streaming"]).lower()}, '
            f'WebSocket: {str(row["websocket"]).lower()}, PathParameters: []string{{{parameters}}}}},'
        )
    source = f'''// Code generated by scripts/generate_openapi.py; DO NOT EDIT.

package client

import (
\t"fmt"
\t"net/url"
\t"strings"
)

const openAPISpecSHA256 = "{digest}"

type openAPIOperationID string

const (
{constants}
)

type openAPIOperation struct {{
\tMethod           string
\tPath             string
\tAuthLane         string
\tSigning          string
\tStreamingRequest bool
\tWebSocket        bool
\tPathParameters   []string
}}

var openAPIOperationTable = map[openAPIOperationID]openAPIOperation{{
{chr(10).join(table_rows)}
}}

func resolveOpenAPIOperation(id openAPIOperationID, pathParameters map[string]string, query url.Values) (openAPIOperation, error) {{
\toperation, ok := openAPIOperationTable[id]
\tif !ok {{
\t\treturn openAPIOperation{{}}, fmt.Errorf("postgrip-agent: unknown OpenAPI operation %q", id)
\t}}
\tfor _, name := range operation.PathParameters {{
\t\tvalue, exists := pathParameters[name]
\t\tif !exists {{
\t\t\treturn openAPIOperation{{}}, fmt.Errorf("postgrip-agent: OpenAPI operation %q requires path parameter %q", id, name)
\t\t}}
\t\toperation.Path = strings.ReplaceAll(operation.Path, "{{"+name+"}}", url.PathEscape(value))
\t}}
\tif encoded := query.Encode(); encoded != "" {{
\t\toperation.Path += "?" + encoded
\t}}
\treturn operation, nil
}}
'''
    try:
        formatted = subprocess.run(
            ["gofmt"], input=source, text=True, capture_output=True, check=True
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as exc:
        raise RuntimeError("gofmt is required to generate OpenAPI bindings") from exc
    return formatted.stdout


def typescript_source(rows: list[dict[str, Any]], digest: str) -> str:
    entries = []
    for row in rows:
        entry = {
            "method": row["method"],
            "path": row["path"],
            "authLane": row["auth"],
            "signing": row["signing"] or None,
            "streamingRequest": row["streaming"],
            "webSocket": row["websocket"],
            "pathParameters": row["parameters"],
        }
        entries.append(f'  {row["id"]}: {json.dumps(entry, separators=(",", ":"))},')
    return f'''// Code generated by scripts/generate_openapi.py; DO NOT EDIT.

export const OPENAPI_SPEC_SHA256 = '{digest}';

const operationTable = {{
{chr(10).join(entries)}
}} as const;

export type OpenAPIOperationId = keyof typeof operationTable;
export type OpenAPIAuthLane = 'agent' | 'either' | 'management' | 'public';

export interface ResolvedOpenAPIOperation {{
  readonly id: OpenAPIOperationId;
  readonly method: string;
  readonly path: string;
  readonly authLane: OpenAPIAuthLane;
  readonly signing?: string;
  readonly streamingRequest: boolean;
  readonly webSocket: boolean;
}}

export function resolveOpenAPIOperation(
  id: OpenAPIOperationId,
  pathParameters: Readonly<Record<string, string>> = {{}},
  query?: URLSearchParams,
): ResolvedOpenAPIOperation {{
  const source = operationTable[id];
  let resolvedPath: string = source.path;
  for (const name of source.pathParameters) {{
    const value = pathParameters[name];
    if (value == null) {{
      throw new Error(`postgrip-agent: OpenAPI operation ${{id}} requires path parameter ${{name}}`);
    }}
    resolvedPath = resolvedPath.replace(`{{${{name}}}}`, encodeURIComponent(value));
  }}
  const encodedQuery = query?.toString();
  if (encodedQuery) resolvedPath += `?${{encodedQuery}}`;
  return {{
    id,
    method: source.method,
    path: resolvedPath,
    authLane: source.authLane,
    ...(source.signing ? {{ signing: source.signing }} : {{}}),
    streamingRequest: source.streamingRequest,
    webSocket: source.webSocket,
  }};
}}
'''


def python_source(rows: list[dict[str, Any]], digest: str) -> str:
    enum_rows = "\n".join(f'    {snake_name(row["id"])} = {row["id"]!r}' for row in rows)
    table_rows = []
    for row in rows:
        params = repr(tuple(row["parameters"]))
        table_rows.append(
            f'    OperationId.{snake_name(row["id"])}: OpenAPIOperation('
            f'{row["method"]!r}, {row["path"]!r}, {row["auth"]!r}, {row["signing"]!r}, '
            f'{row["streaming"]!r}, {row["websocket"]!r}, {params}),'
        )
    return f'''# Code generated by scripts/generate_openapi.py; DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import re
from typing import Mapping, Sequence
from urllib.parse import quote, urlencode

OPENAPI_SPEC_SHA256 = {digest!r}


class OperationId(str, Enum):
{enum_rows}


@dataclass(frozen=True)
class OpenAPIOperation:
    method: str
    path: str
    auth_lane: str
    signing: str
    streaming_request: bool
    websocket: bool
    path_parameters: tuple[str, ...]


@dataclass(frozen=True)
class ResolvedOpenAPIOperation:
    operation_id: OperationId
    method: str
    path: str
    auth_lane: str
    signing: str
    streaming_request: bool
    websocket: bool


_OPERATION_TABLE: dict[OperationId, OpenAPIOperation] = {{
{chr(10).join(table_rows)}
}}


def openapi_auth_lane_for_request(method: str, path: str) -> str | None:
    """Return the generated auth lane for a raw request when it is known."""
    request_path = path.partition("?")[0]
    for operation in _OPERATION_TABLE.values():
        if operation.method != method.upper():
            continue
        pattern = re.sub(r"\\{{[^}}]+\\}}", r"[^/]+", operation.path)
        if re.fullmatch(pattern, request_path):
            return operation.auth_lane
    return None


def resolve_openapi_operation(
    operation_id: OperationId,
    path_parameters: Mapping[str, str] | None = None,
    query: Mapping[str, object] | Sequence[tuple[str, object]] | None = None,
) -> ResolvedOpenAPIOperation:
    source = _OPERATION_TABLE[operation_id]
    values = path_parameters or {{}}
    resolved_path = source.path
    for name in source.path_parameters:
        if name not in values:
            raise ValueError(
                f"postgrip-agent: OpenAPI operation {{operation_id.value}} "
                f"requires path parameter {{name}}"
            )
        resolved_path = resolved_path.replace("{{" + name + "}}", quote(values[name], safe=""))
    if query:
        resolved_path += "?" + urlencode(query, doseq=True)
    return ResolvedOpenAPIOperation(
        operation_id=operation_id,
        method=source.method,
        path=resolved_path,
        auth_lane=source.auth_lane,
        signing=source.signing,
        streaming_request=source.streaming_request,
        websocket=source.websocket,
    )
'''


def generated_files(spec: dict[str, Any], digest: str) -> dict[Path, str]:
    rows = operation_rows(spec)
    return {
        ROOT / "go" / "client" / "openapi_operations.gen.go": go_source(rows, digest),
        ROOT / "typescript" / "src" / "generated" / "openapi.ts": typescript_source(rows, digest),
        ROOT / "python" / "src" / "postgrip_agent" / "generated" / "__init__.py":
            "# Internal generated OpenAPI bindings.\n",
        ROOT / "python" / "src" / "postgrip_agent" / "generated" / "openapi.py": python_source(rows, digest),
    }


def write_or_check(outputs: dict[Path, str], check: bool) -> bool:
    dirty: list[Path] = []
    for output_path, expected in outputs.items():
        if check:
            if not output_path.exists() or output_path.read_text() != expected:
                dirty.append(output_path.relative_to(ROOT))
            continue
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(expected)
    if dirty:
        print("Generated OpenAPI bindings are stale:", file=sys.stderr)
        for output_path in dirty:
            print(f"- {output_path}", file=sys.stderr)
        print("Run: python3 scripts/generate_openapi.py", file=sys.stderr)
        return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail instead of rewriting stale output")
    parser.add_argument("--check-source", type=Path, help="verify openapi.json matches the canonical source")
    args = parser.parse_args()

    if args.check_source and SPEC_PATH.read_bytes() != args.check_source.resolve().read_bytes():
        print(f"openapi.json differs from canonical source {args.check_source}", file=sys.stderr)
        return 1

    spec, digest = load_contract()
    outputs = generated_files(spec, digest)
    if not write_or_check(outputs, args.check):
        return 1
    action = "verified" if args.check else "generated"
    print(f"OpenAPI bindings {action}: {len(operation_rows(spec))} operations ({digest[:12]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
